### ISSUE TITLE
Loading screen softlock and potential save bricking.

### ISSUE THREAD

**Issue by BROHONKY** [BRCMapStation/MapStation#5]
Something I noticed is how when loading into a map you have uninstalled, the loading screen gets stuck trying to load it. That on it's own is kind of annoying but not really a huge issue. But I could see an issue where if you quit playing on a custom map then for whatever reason that map gets erased either because you deleted the test map or because the original creator removed it, that could potentially brick your save since there's no map to go back to.

**Comment by cspotcode** [comment]
Closing because the crash detector should avoid this.
